# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    environment:
      BROWSERSTACK_LOCAL: "true"
      BROWSERSTACK_LOCAL_IDENTIFIER: "identifier"
    docker:
      - image: cimg/node:14.11.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: sudo npm install -g browserstack-cypress-cli
      - run:
          name: "Run the test on BrowserStack"
          command: browserstack-cypress --config-file run_conf/bstack-local-single.json run --sync --spec --parallels 5

workflows:
  build:
    jobs:
      - build
    #       pre-steps:
    # # Download the browserstack binary file
    #         - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
    #         # Unzip the BrowserStack Local binary file
    #         - unzip BrowserStackLocal-linux-x64.zip
    #         # Run the file with your access key
    #         - ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY:
    #             background: true
